# SPDX-FileCopyrightText: 2026 KWin AutoScroll contributors
# SPDX-License-Identifier: CC0-1.0

[options]
Architecture = x86_64
CheckSpace
ParallelDownloads = 8
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

[jupiter-3.8]
Server = https://steamdeck-packages.steamos.cloud/archlinux-mirror/$repo/os/$arch

[holo-3.8]
Server = https://steamdeck-packages.steamos.cloud/archlinux-mirror/$repo/os/$arch

[core-3.8]
Server = https://steamdeck-packages.steamos.cloud/archlinux-mirror/$repo/os/$arch

[extra-3.8]
Server = https://steamdeck-packages.steamos.cloud/archlinux-mirror/$repo/os/$arch
