# SPDX-FileCopyrightText: 2026 KWin AutoScroll contributors
# SPDX-License-Identifier: CC0-1.0

[options]
Architecture = x86_64
CheckSpace
ParallelDownloads = 8
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

[jupiter-main]
Server = https://steamdeck-packages.steamos.cloud/archlinux-mirror/$repo/os/$arch

[holo-main]
Server = https://steamdeck-packages.steamos.cloud/archlinux-mirror/$repo/os/$arch

[core-main]
Server = https://steamdeck-packages.steamos.cloud/archlinux-mirror/$repo/os/$arch

[extra-main]
Server = https://steamdeck-packages.steamos.cloud/archlinux-mirror/$repo/os/$arch

[community-main]
Server = https://steamdeck-packages.steamos.cloud/archlinux-mirror/$repo/os/$arch
